version: '3.8'

services:
  rup-api-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rup-api-satker-dev
    restart: unless-stopped
    ports:
      - "8080:8080"  # Development port
    environment:
      - NODE_ENV=development
      - PORT=8080
      - DEFAULT_KLPD=D197
      - DEFAULT_TAHUN=2025
      - DEBUG=true
    volumes:
      # Mount source code untuk development (hot reload)
      - ./src:/app/src:ro
      - ./logs:/app/logs
      # Mount node_modules untuk performance
      - node_modules:/app/node_modules
    networks:
      - rup-dev-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s
    # Development resource limits (lebih generous)
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 128M

networks:
  rup-dev-network:
    driver: bridge

volumes:
  node_modules:
    driver: local
